# Generated by Django 5.1.7 on 2025-05-25 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepty', '0005_ingredient_description_ingredient_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipe_images/'),
        ),
    ]
